# $NetBSD$
#

COMMENT=	Document format and character code converters

SUBDIR+=	help2man
SUBDIR+=	libiconv
SUBDIR+=	p5-MIME-Base64
SUBDIR+=	p5-Unicode-EastAsianWidth
SUBDIR+=	py-simplejson

.include "../mk/misc/category.mk"
