# $NetBSD$
#

COMMENT=	Security tools

SUBDIR+=	gnupg
SUBDIR+=	libgcrypt
SUBDIR+=	libgpg-error
SUBDIR+=	libsodium
SUBDIR+=	libssh2
SUBDIR+=	mozilla-rootcerts
SUBDIR+=	netpgpverify
SUBDIR+=	openssh
SUBDIR+=	openssl
SUBDIR+=	p5-Authen-SASL
SUBDIR+=	p5-Digest-HMAC
SUBDIR+=	p5-Digest-MD5
SUBDIR+=	p5-Digest-SHA
SUBDIR+=	p5-IO-Socket-SSL
SUBDIR+=	p5-Mozilla-CA
SUBDIR+=	p5-Net-SSLeay
SUBDIR+=	py-crypto
SUBDIR+=	py-m2crypto
SUBDIR+=	ruby-shadow
SUBDIR+=	sudo
SUBDIR+=	tcp_wrappers

.include "../mk/misc/category.mk"
