# $NetBSD$
#

COMMENT=	Archivers

SUBDIR+=	bsdtar
SUBDIR+=	bzip2
SUBDIR+=	gtar
SUBDIR+=	gtar-base
SUBDIR+=	gtar-info
SUBDIR+=	gzip
SUBDIR+=	libarchive
SUBDIR+=	pax
SUBDIR+=	unzip
SUBDIR+=	xz

.include "../mk/misc/category.mk"
