# $NetBSD$

DISTNAME=		texttable-0.8.3
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		textproc
MASTER_SITES=		https://pypi.python.org/packages/source/t/texttable/

MAINTAINER=		pkgsrc@cargos.io
HOMEPAGE=		https://pypi.python.org/pypi/texttable
COMMENT=		Python module for creating simple ASCII tables
LICENSE=		gnu-lgpl-v3

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
