# $NetBSD$

DISTNAME=		virt-what-1.15
CATEGORIES=		sysutils
MASTER_SITES=		http://people.redhat.com/~rjones/virt-what/files/

MAINTAINER=		pkgsrc@cargos.io
HOMEPAGE=		http://people.redhat.com/~rjones/virt-what/
COMMENT=		Detect if we are running in a virtual machine
LICENSE=		gnu-gpl-v2

GNU_CONFIGURE=		Yes

.include "../../mk/bsd.pkg.mk"
