# $NetBSD$

DISTNAME=		dockerpty-0.3.2
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		sysutils
MASTER_SITES=		https://pypi.python.org/packages/source/d/dockerpty/

MAINTAINER=		pkgsrc@cargos.io
HOMEPAGE=		https://pypi.python.org/pypi/dockerpty
COMMENT=		Python library to use the pseudo-tty of a docker container
LICENSE=		apache-2.0

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
