# $NetBSD$

DISTNAME=		websocket_client-0.26.0
PKGNAME=		${PYPKGPREFIX}-${DISTNAME:S/_/-/}
CATEGORIES=		textproc
MASTER_SITES=		https://pypi.python.org/packages/source/w/websocket-client/

MAINTAINER=		pkgsrc@cargos.io
HOMEPAGE=		https://pypi.python.org/pypi/websocket-client
COMMENT=		WebSocket client for python
LICENSE=		gnu-lgpl-v2.1

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
