# $NetBSD$
#

COMMENT=	Programming languages

SUBDIR+=	gawk
SUBDIR+=	gcc49
SUBDIR+=	gcc49-libs
SUBDIR+=	go
SUBDIR+=	perl5
SUBDIR+=	python27
SUBDIR+=	ruby
SUBDIR+=	ruby200-base
SUBDIR+=	runawk
SUBDIR+=	tcl

.include "../mk/misc/category.mk"
