# $NetBSD$
#

COMMENT=	Tools for use in the packages collection

SUBDIR+=	bootstrap-mk-files
SUBDIR+=	digest
SUBDIR+=	libnbcompat
SUBDIR+=	pkg_install
SUBDIR+=	pkg_install-info
SUBDIR+=	pkg_summary-utils
SUBDIR+=	pkgin

.include "../mk/misc/category.mk"
