# $NetBSD$

DISTNAME=		docker-py-1.1.0
PKGNAME=		${PYPKGPREFIX}-${DISTNAME:S/-py//}
CATEGORIES=		sysutils
MASTER_SITES=		https://pypi.python.org/packages/source/d/docker-py/

MAINTAINER=		pkgsrc@cargos.io
HOMEPAGE=		https://pypi.python.org/pypi/dockerpty
COMMENT=		Python client for Docker
LICENSE=		apache-2.0

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
