# $NetBSD$
#

COMMENT=	Text processing utilities (does not include desktop publishing)

SUBDIR+=	asciidoc
SUBDIR+=	docbook-xml
SUBDIR+=	docbook-xsl
SUBDIR+=	expat
SUBDIR+=	groff
SUBDIR+=	gsed
SUBDIR+=	libxml2
SUBDIR+=	libxslt
SUBDIR+=	libyaml
SUBDIR+=	mdocml
SUBDIR+=	p5-Text-Unidecode
SUBDIR+=	py-expat
SUBDIR+=	py-jinja2
SUBDIR+=	py-markupsafe
SUBDIR+=	py-yaml
SUBDIR+=	ruby-json-pure
SUBDIR+=	xmlcatmgr
SUBDIR+=	xmlto

.include "../mk/misc/category.mk"
