# $NetBSD$
#

COMMENT=	System utilities

SUBDIR+=	coreutils
SUBDIR+=	dmidecode
SUBDIR+=	file
SUBDIR+=	findutils
SUBDIR+=	grub2
SUBDIR+=	install-sh
SUBDIR+=	puppet
SUBDIR+=	ruby-facter
SUBDIR+=	salt

.include "../mk/misc/category.mk"
