# $NetBSD$
#

COMMENT=	Networking tools

SUBDIR+=	libfetch
SUBDIR+=	libpcap
SUBDIR+=	p5-IO-Socket-INET6
SUBDIR+=	p5-Net
SUBDIR+=	p5-Net-DNS
SUBDIR+=	p5-Net-Domain-TLD
SUBDIR+=	p5-Net-IP
SUBDIR+=	p5-Net-LibIDN
SUBDIR+=	p5-Socket6
SUBDIR+=	py-apache-libcloud
SUBDIR+=	py-zmq
SUBDIR+=	rsync
SUBDIR+=	tcpdump
SUBDIR+=	wget
SUBDIR+=	zeromq

.include "../mk/misc/category.mk"
